theme = "tokyonight"
use-fork = true

[cursor]
shape = 'beam'
blinking = true
blinking-interval = 800

[editor]
program = "nvim"

[window]
opacity = 0.9
blur = false
decorations = "disabled"
colorspace = "rec2020"

[renderer]
performance = "high"
backend = "vulkan"
target-fps = 75
disable-unfocused-render = false
level = 1
# filters = []

[fonts]
size = 15
family = "JetBrainsMono Nerd Font"
use-drawable-chars = true

[fonts.regular]
style = "Normal"
weight = 500

[fonts.bold]
style = "Normal"
weight = 800

[fonts.italic]
style = "Italic"
weight = 500

[fonts.bold-italic]
style = "Italic"
weight = 800
